### ISSUE TITLE
Icône fontawesome

### ISSUE THREAD

**Issue by XCarrel** [CPNV-INFO/CSUNVB#41]
Dans la liste des Todos, remplacer le marqueur de template 
![image](https://user-images.githubusercontent.com/7465241/102009098-76c33e00-3d35-11eb-8a8e-cdb43fe0c65f.png)
par un [icône fontawesome](https://fontawesome.com/icons?d=gallery) pour une meilleure unité graphique

**Comment by Bluebottle39** [comment]
Changement effectué
