### ISSUE TITLE
Etat du rapport - Garde

### ISSUE THREAD

**Issue by XCarrel** [CPNV-INFO/CSUNVB#42]
Quand je consulte ou édite un rapport de garde, il faut afficher son état actuel, du genre:
![image](https://user-images.githubusercontent.com/7465241/102009262-84c58e80-3d36-11eb-9e19-2acfdbd6aac3.png)

**Comment by AhVen98** [comment]
L'état s'affiche correctement, selon les données présentes dans la base de données. 
La fonction est prévue pour être commune sur toutes les parties
![blank](https://user-images.githubusercontent.com/56110370/102127805-3d7df180-3e4d-11eb-93ee-c250f82e9f61.png)
