### ISSUE TITLE
Etat du rapport - Todo

### ISSUE THREAD

**Issue by XCarrel** [CPNV-INFO/CSUNVB#43]
Quand je consulte ou édite un rapport de garde, il faut afficher son état actuel, du genre:
![image](https://user-images.githubusercontent.com/7465241/102009262-84c58e80-3d36-11eb-9e19-2acfdbd6aac3.png)

**Comment by AhVen98** [comment]
l'état s'affiche (il faut par contre aller modifier la BDD de données pour récupérer l'état de manière dynamique et non pas le donner de manière fixe)
