### ISSUE TITLE
affichage des colonnes d'un rapport todo

### ISSUE THREAD

**Issue by MichaelGogniat** [CPNV-INFO/CSUNVB#58]
sur tablette, ou autre écran de plus petite taille, toute les colonne de sont pas affichée à la suite, et elle ne sont pas alignée avec le nom du jour[](url)

**Comment by MichaelGogniat** [comment]
<img width="305" alt="issue" src="https://user-images.githubusercontent.com/56110431/104347030-6ce15600-5500-11eb-86cd-ccd0a34b4c6e.PNG">

**Comment by Kalysso** [comment]
Pose également problème pour la génération du PDF

**Comment by XCarrel** [comment]
L'affichage est également incorrect sur grand écran.
![image](https://user-images.githubusercontent.com/7465241/106280728-90193e80-623e-11eb-9cef-1109e24e6cc2.png)
