### ISSUE TITLE
Retour de remise de garde

### ISSUE THREAD

**Issue by XCarrel** [CPNV-INFO/CSUNVB#79]
remplacer 'Retour'
![image](https://user-images.githubusercontent.com/7465241/112992964-fb14c200-9168-11eb-9922-c378536bcae5.png)
par 
![image](https://user-images.githubusercontent.com/7465241/112993681-c05f5980-9169-11eb-9be4-7697199a5ec8.png)
comme dans les autres rapports

**Comment by MichaelGogniat** [comment]
la version sur les rapports de garde est similaire à celle des todos, elle a pour but d'alléger la page
êtes vous sûr de vouloir revenir en arrière sur ces deux types de rapports ?

**Comment by XCarrel** [comment]
Remplacé par une navigation homogène sans bouton, basée sur les liens de la barre de nav
