### ISSUE TITLE
Présentation des rapports de stup

### ISSUE THREAD

**Issue by XCarrel** [CPNV-INFO/CSUNVB#90]
Pour améliorer la lisibilité des rapports de stupéfiant, nous allons utiliser les même couleurs que pour les rapports de garde couleurs (bleu clair = jour, noir = nuit) et utiliser des coins arrondis pour représenter le matin et le soir.
Cela donne quelque chose comme ça:
![image](https://user-images.githubusercontent.com/7465241/117528898-c819e580-afd4-11eb-80a3-9e0b9cb48210.png)

**Comment by XCarrel** [comment]
J'ai trafiqué le html d'une page existante pour arriver à ça, voici un snippet en guise d'aide:
```
<td class="text-center">
    <div class="w-25 d-inline" style="background-color:lightblue; padding:10px; margin-right:0px; border-top-left-radius: 50%;border-bottom-left-radius: 50%;">6</div>
    <div class="w-25 d-inline" style="background-color:black; color:white; padding:10px; margin-left:0px; border-top-right-radius: 50%;border-bottom-right-radius: 50%;">6</div>
</td>
```

**Comment by SemicolonManifest** [comment]
Ce changement à été effectué.
